### ISSUE TITLE
Audio not working on Acer CB 13 / Akili Kabylake 

### ISSUE THREAD

**Issue by geekmystique** [eupnea-linux/audio-scripts#12]
Thanks for the project revival!

Running PopOS;
Ran the kernel script, setup audio after reboot, output:

```
Verbosity increased
WARNING: this audio script is not fully functional yet!
Installing AVS
avs audio is not implemented yet!
Audio installed successfully! Reboot to enable audio.
Press ENTER to reboot or CTRL+C to cancel reboot
```

```
lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 02)
00:02.0 VGA compatible controller: Intel Corporation Device 5906 (rev 02)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 02)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #0 (rev 21)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #1 (rev 21)
00:15.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #2 (rev 21)
00:15.3 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO I2C Controller #3 (rev 21)
00:19.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO UART Controller #2 (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #4 (rev f1)
00:1e.0 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO UART Controller #0 (rev 21)
00:1e.2 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO SPI Controller #0 (rev 21)
00:1e.3 Signal processing controller: Intel Corporation Sunrise Point-LP Serial IO SPI Controller #1 (rev 21)
00:1e.4 SD Host controller: Intel Corporation Device 9d2b (rev 21)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Multimedia audio controller: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
00:1f.5 Non-VGA unclassified device: Intel Corporation Device 9d24 (rev 21)
01:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)

```
```

/sbin/lsmod | grep snd
snd_soc_hdac_hdmi      45056  0
snd_soc_dmic           16384  0
snd_soc_skl_ssp_clk    16384  0
snd_soc_skl           184320  1 snd_soc_skl_ssp_clk
snd_soc_hdac_hda       24576  1 snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        40960  1 snd_soc_skl
snd_soc_acpi_intel_match    53248  1 snd_soc_skl
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_soc_skl
snd_hda_ext_core       36864  3 snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl
snd_hda_intel          53248  0
snd_intel_dspcfg       20480  2 snd_hda_intel,snd_soc_skl
snd_hda_codec         163840  2 snd_hda_intel,snd_soc_hdac_hda
snd_hwdep              16384  1 snd_hda_codec
snd_hda_core          106496  6 snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl
snd_soc_da7219         81920  0
snd_soc_max98357a      20480  0

```

**Comment by WeirdTreeThing** [comment]
AVS on KabyLake is currently not supported. If you would like to I need people to test it so I can add support.

**Comment by geekmystique** [comment]
Sure let me know what you need, i won't be angry if you blow up the speakers or cause other damage- it is a hobby project for me.

**Comment by WeirdTreeThing** [comment]
Thanks for helping me test it. I created a script which should get avs working. https://cdn.discordapp.com/attachments/1012862128887173243/1036013573966659614/avs-sklkbl.sh

**Comment by geekmystique** [comment]
Thanks so far!
Tried 3 combinations, no luck; only dummy audio output. The script runs without error. 
Clean update-kernel --alt and clean install --> update-kernel --mainline + script
After update-kernel --mainline i get uname -r --> 6.0.0

Please let me know what i can run to debug further

**Comment by WeirdTreeThing** [comment]
AVS will only work with the mainline kernel. Please create a clean install with the mainline kernel, run the avs script, then run collect-logs and upload the file it creates to https://www.uguu.se and send the link.

**Comment by geekmystique** [comment]
ok did a clean image generation with --mainline - unfortunately still dummy only. 

collect-logs threw this error:
Collecting firmware tree
Traceback (most recent call last):
  File "/usr/local/bin/collect-logs", line 127, in <module>
    system_info()
  File "/usr/local/bin/collect-logs", line 86, in system_info
    file.write(create_tree("/lib/firmware"))
NameError: name 'create_tree' is not defined

Outputs:
https://a.uguu.se/LHCGTMdU.gz
https://a.uguu.se/kMQOhxwq.tar

So i commented out those lines and pulled the ucm2 and lib/firmware trees by hand.

**Comment by Apacelus** [comment]
@geekmystique the functions.py file didnt get updated, my bad. Please run ``update-scripts`` and try again

**Comment by geekmystique** [comment]
Awesome, logs worked now!
https://a.uguu.se/kUkbqguP.gz

**Comment by Apacelus** [comment]
In case the link goes down:
[eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/9896551/eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Looks like the sst driver is trying to load. Run `echo "blacklist snd_soc_skl" > /etc/modprobe.d/blacklist-sst.conf` to fix it.

**Comment by geekmystique** [comment]
Thanks! 
Unfortunately still no-go... Also noticed standby is broken now- i guess due to mainline? But ok let's focus on the audio first ;)
New log collect: https://a.uguu.se/auqNzZdi.gz

**Comment by WeirdTreeThing** [comment]
I just push a new release of the mainline kernel which enables AVS. To update run `update-kernel --mainline`.

**Comment by Apacelus** [comment]
@geekmystique can you please upload the logs directly to github. They might be useful in the future

**Comment by geekmystique** [comment]
Unfortunately still no-go after kernel update, reboot.. also tried to run the avs script again... no luck. Logs attached.
[2022-10-30_21h-16m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/9896754/2022-10-30_21h-16m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Try `modprobe snd_soc_avs` and `modprobe snd_intel_dspcfg dsp_driver=4`

**Comment by geekmystique** [comment]
nope.. still nothing :/ 
[2022-10-30_21h-40m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/9896785/2022-10-30_21h-40m-eupnea-logs.tar.gz)

Thanks for the effort !

**Comment by WeirdTreeThing** [comment]
I'm all out of ideas for now. I will look into this later.

**Comment by WeirdTreeThing** [comment]
@geekmystique run `echo "options snd-intel-dspcfg dsp_driver=4" > /etc/modprobe.d/snd.conf` and send logs.

**Comment by WeirdTreeThing** [comment]
@geekmystique I have added support for avs on kbl. Run `update-scripts` and `setup-audio`.

**Comment by WeirdTreeThing** [comment]
This issue is solved.

**Comment by WeirdTreeThing** [comment]
max98357a/da7219 works on kabylake.
