### ISSUE TITLE
Google Pixel Slate Nocturne

### ISSUE THREAD

**Issue by betolley** [eupnea-linux/audio-scripts#13]
I tried to load the with both mainline and alt kernel.  Here is the error in dmesg:
   10.050795] snd_soc_skl 0000:00:1f.3: skl_cldma_wait_interruptible: Wait timeout
[   10.052008] snd_soc_skl 0000:00:1f.3: Failed to set Run bit=2 enable=0
[   10.052010] snd_soc_skl 0000:00:1f.3: Transfer firmware failed-5
[   10.053217] snd_soc_skl 0000:00:1f.3: Failed to set Run bit=2 enable=0
[   10.053803] snd_soc_skl 0000:00:1f.3: Load base fw failed : -5
[   10.053812] snd_soc_skl 0000:00:1f.3: Failed to boot first fw: -5
[   10.053814] snd_soc_skl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -5
[   10.053880] kbl_da7219_max98_927_373 kbl_max98373: ASoC: failed to instantiate card -5

I also tried copying the /lib/firmware files over from the cros install when nothing else worked.  Before without the firmware I was getting a firmware error.

**Comment by Apacelus** [comment]
Did the error go away after copying the firmware?

Also, actually the build script downloads the chromeos firmware, so there should be no need to copy it

**Comment by betolley** [comment]
Yes the error about missing firmware went away but I have the above message.

**Comment by WeirdTreeThing** [comment]
IIRC pixel devices have extra issues with audio.

**Comment by betolley** [comment]
If i use chrx and copy over the firmware I can get kblmax98373 to load 
!!Sound Servers on this system
!!----------------------------

PipeWire:
      Installed - Yes (/usr/bin/pipewire)
      Running - Yes

No sound servers found.


!!Soundcards recognised by ALSA
!!-----------------------------

 0 [kblmax98373    ]: kblmax98373 - kblmax98373
                      Google-Nocturne-1.0


!!PCI Soundcards installed in the system
!!--------------------------------------

00:1f.3 Multimedia audio controller [0401]: Intel Corporation Sunrise Point-LP HD Audio [8086:9d71] (rev 21)
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-


But but I get in dmesg:

[   64.535578]  Kbl Audio DMIC cap: ASoC: dpcm_fe_dai_hw_params failed (-22)
[   64.536333] snd_soc_skl 0000:00:1f.3: Blob NULL for id:0 type:2 dirn:1 ch:4, freq:48000, fmt:24
[   64.536342] snd_soc_skl 0000:00:1f.3: ASoC: error at snd_soc_dai_hw_params on DMIC01 Pin: -22
[   64.536369]  dmic01: ASoC: __soc_pcm_hw_params() failed (-22)
[   64.536373]  Kbl Audio DMIC cap: ASoC: dpcm_fe_dai_hw_params failed (-22)

**Comment by WeirdTreeThing** [comment]
Nocturne now has support.
