### ISSUE TITLE
How to get audio to work in Intel Apollo Lake?

### ISSUE THREAD

**Issue by kovan** [eupnea-linux/audio-scripts#15]
Is it possible?.

I have installed Ubuntu and the rest works really well.

Just to test, I have tried calling sof_audio() in the setup-audio script with no success.

Let me know if I can be of help.

Thank you for your time.

**Comment by WeirdTreeThing** [comment]
SOF on apollo lake has multiple issues. The new driver AVS fixes all of that. I need people to test it so if you would like to help you can use [this](https://cdn.discordapp.com/attachments/1012864503693721733/1036013640706428928/avs-apl.sh) script, you also need the mainline kernel. Just a warning that if you go above 60% volume on speakers they will blow up so just stay below 60%. Headphones don't have this problem.

**Comment by kovan** [comment]
OK, I will test it, but what kernel is the mainline kernel?

**Comment by Apacelus** [comment]
@kovan run ``update-kernel --mainline`` to update automatically

**Comment by kovan** [comment]
I upgraded the kernel to mainline.
Just by running the script nothing seems to change:

$ aplay -l
> aplay: device_list:274: no soundcards found...

$ sudo dmesg  | grep 'audio\|snd'
> [    6.378735] snd_hda_intel 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    6.545461] snd_soc_skl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    6.855831] snd_soc_skl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops)
[    7.653036] HDMI HDA Codec ehdaudio0D2: Max dais supported: 3
[    7.670172] snd_soc_skl 0000:00:0e.0: Direct firmware load for 5a98-coral-coral-30-tplg.bin **failed with error -2**
[    7.670187] snd_soc_skl 0000:00:0e.0: tplg fw 5a98-coral-coral-30-tplg.bin **load failed with -2**, trying alternative tplg name bxt_da7219_mx98357a-tplg.bin
[    7.670240] snd_soc_skl 0000:00:0e.0: Direct firmware load for bxt_da7219_mx98357a-tplg.bin **failed with error -2**
[    7.670243] snd_soc_skl 0000:00:0e.0: tplg bxt_da7219_mx98357a-tplg.bin _**failed with -2**_, falling back to dfw_sst.bin
[    7.670300] snd_soc_skl 0000:00:0e.0: Direct firmware load for dfw_sst.bin _**failed with error -2**_
[    7.670304] snd_soc_skl 0000:00:0e.0: Fallback tplg fw dfw_sst.bin _**load failed with -2**_
[    7.670311] snd_soc_skl 0000:00:0e.0: _**Failed to init topology!**_
[    7.670314] snd_soc_skl 0000:00:0e.0: _**ASoC: error at snd_soc_component_probe on 0000:00:0e.0: -2**_

Looks like the kernel is trying to enable SoC, not AVS, and for the skl platform, not Apollo Lake.

$ lspci -k
> ...
00:0e.0 Multimedia audio controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster (rev 0b)
        Subsystem: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
        Kernel driver in use: snd_soc_skl
        Kernel modules: snd_hda_intel, snd_soc_skl, snd_sof_pci_intel_apl
...

$ lsmod | grep snd
> snd_soc_sst_bxt_da7219_max98357a    28672  0
snd_soc_intel_hda_dsp_common    20480  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_hdac_hdmi      45056  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  0
snd_soc_skl_ssp_clk    16384  0
snd_sof_pci_intel_apl    16384  0
snd_sof_intel_hda_common   143360  1 snd_sof_pci_intel_apl
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
snd_sof_pci            24576  2 snd_sof_intel_hda_common,snd_sof_pci_intel_apl
snd_sof_xtensa_dsp     16384  1 snd_sof_intel_hda_common
snd_sof               241664  2 snd_sof_pci,snd_sof_intel_hda_common
snd_sof_utils          20480  1 snd_sof
snd_soc_skl           180224  1 snd_soc_skl_ssp_clk
snd_soc_hdac_hda       24576  2 snd_sof_intel_hda_common,snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        40960  1 snd_soc_skl
snd_soc_acpi_intel_match    69632  3 snd_sof_intel_hda_common,snd_soc_skl,snd_sof_pci_intel_apl
snd_hda_ext_core       36864  5 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_acpi           16384  3 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_soc_skl
snd_hda_intel          53248  0
snd_intel_dspcfg       32768  4 snd_hda_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_skl
snd_hda_codec         172032  3 snd_hda_intel,snd_soc_intel_hda_dsp_common,snd_soc_hdac_hda
snd_hwdep              16384  1 snd_hda_codec
snd_hda_core          114688  9 snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_intel_hda_dsp_common,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_soc_max98357a      20480  0
snd_soc_da7219         86016  1 snd_soc_sst_bxt_da7219_max98357a

**Comment by WeirdTreeThing** [comment]
The skl driver is just sst which supports apl. To fix sst loading run `echo "blacklist snd_soc_skl" > /etc/modprobe.d/blacklist-sst.conf`

**Comment by WeirdTreeThing** [comment]
Actually it looks like the avs driver isnt even loaded.

**Comment by kovan** [comment]
Right. Where is it?
`$ find /lib/modules* | grep avs` yields nothing.

**Comment by WeirdTreeThing** [comment]
Are you sure you are on mainline?

**Comment by kovan** [comment]
Yeah yeah 

uname -a
`Linux ubuntu 6.0.0 #1 SMP PREEMPT_DYNAMIC Thu Oct 27 10:10:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by WeirdTreeThing** [comment]
Looks like I forgot to enable AVS in the kernel config. I will push a fix in a few mintues and it will take about an hour for the new kernel to build.

**Comment by kovan** [comment]
OK thx.

**Comment by WeirdTreeThing** [comment]
I just push a new release of the mainline kernel which enables AVS. To update run `update-kernel --mainline`.

**Comment by kovan** [comment]
I have updated the kernel, and now the module snd_soc_avs is loaded, but still is not being used:

lspci:
> 00:0e.0 Multimedia audio controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster (rev 0b)
>         Subsystem: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
>         Kernel modules: snd_hda_intel, snd_soc_skl, snd_soc_avs, snd_sof_pci_intel_apl

$ lsmod | grep snd | grep avs

> snd_soc_avs           143360  0
> snd_soc_hda_codec      24576  1 snd_soc_avs
> snd_hda_ext_core       36864  5 snd_soc_avs,snd_soc_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
> snd_intel_dspcfg       32768  4 snd_soc_avs,snd_hda_intel,snd_sof,snd_sof_intel_hda_common
> snd_hda_codec         172032  4 snd_soc_avs,snd_soc_hda_codec,snd_hda_intel,snd_soc_hdac_hda
> snd_hda_core          114688  8 snd_soc_avs,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_sof_intel_hda
>

**Comment by WeirdTreeThing** [comment]
Run `update-scripts` and `collect-logs` and upload the file it creates.

**Comment by kovan** [comment]
I ran update-scripts and it ran fine except an error at the end:

> ...
> Copying scripts and configs
> Enabling postinstall service
> Traceback (most recent call last):
>   File "/usr/local/bin/update-scripts", line 82, in <module>
>     cpfile("/etc/systemd/system/postinstall.service.disabled", "/etc/systemd/system/postinstall.service")
>   File "/usr/local/bin/functions.py", line 110, in cpfile
>     raise FileNotFoundError(f"No such file: {src_as_path.absolute().as_posix()}")
> FileNotFoundError: No such file: /etc/systemd/system/postinstall.service.disabled

Here are the logs:
[logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/9897012/logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Reboot and try `update-scripts` again.

**Comment by kovan** [comment]
Ok no error now yay

**Comment by WeirdTreeThing** [comment]
Yes send logs again.

**Comment by kovan** [comment]
[2022-10-31_02h-05m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/9897224/2022-10-31_02h-05m-eupnea-logs.tar.gz)

**Comment by kovan** [comment]
We might just as well wait. After all, all this AVS stuff is very very recent in mainline kernel (like, a couple weeks?).
Also Google will probably upgrade to 6.x kernel in Chromebooks, after all they are using 5.15 now so they seem to be in sync with the stable branch of mainline, and 6.x stable seems to be scheduled for around December.
So either way time is in our favor, and not long times.

**Comment by WeirdTreeThing** [comment]
I was able to get avs to work on my device, I will add support to the script soon.

**Comment by WeirdTreeThing** [comment]
@kovan I made a new branch for avs. You will need to git clone that branch and change line 252 of setup-audio to `config_path = "configs"`.

**Comment by WeirdTreeThing** [comment]
@kovan I added avs to the main script now. Just run `update-scripts` and `setup-audio`.

**Comment by kovan** [comment]
It is working yeah!. Both headphones and speakers are working. Thanks a lot.
Let's see if I can sofware-limit the volume level, just to be safe that speakers don't get damaged.

**Comment by kovan** [comment]
Seems to only happen in KDE though, so back to GNOME, also that would be a different issue.

Continuing with this issue, volume seems to be fine, no excessive loudness at maximum volume.
So I guess we can close this issue? 

My config, for anyone reading this:
- kernel 6.0.7 mainline
- Ubuntu 22.10 with Gnome.

**Comment by WeirdTreeThing** [comment]
If you go above 50% it wont be load but instead too much current gets sent to the speakers which will cause them to burst if you are playing audio for too long.
