### ISSUE TITLE
Debian python version error

### ISSUE THREAD

**Issue by jimbobcraig** [eupnea-linux/audio-scripts#18]
debian / mate installed to internal.

running the setup-audio script yields an error,

`File "/usr/local/bin/setup-audio", line 131
    match operation:
          ^
SyntaxError: invalid syntax
`

**Comment by Apacelus** [comment]
I added a warning to the depthboot script in https://github.com/eupnea-linux/depthboot-builder/commit/9b56bb520dc3e60ad9877607df835378859ee6c8

**Comment by jimbobcraig** [comment]
As detailed above, I upgraded to Python 3.10 and the script now completes without error. Still no audio but i'll open that as a new issue.
