### ISSUE TITLE
Audio not working on Intel Gemini Lake (ASUS Chromebook C204E)

### ISSUE THREAD

**Issue by jimbobcraig** [eupnea-linux/audio-scripts#21]
`setup-audio` script exits with

`Verbosity increased
WARNING: this audio script is not fully functional yet!
Unknown/Unsupported chromebook model: ampton
`

**Comment by WeirdTreeThing** [comment]
Fixed in latest commit. Run `update-scripts` to download the latest version.

**Comment by jimbobcraig** [comment]
The script does not complete. It errors at:

`E: Unable to locate package linux-firmware`

I think, from searching apt, that this should be `firmware-linux`

Making this change locally allows the script to progress until,

`Traceback (most recent call last):
  File "/usr/local/bin/setup-audio", line 256, in <module>
    sof_audio("glk", user_id)
  File "/usr/local/bin/setup-audio", line 52, in sof_audio
    ucmdir = os.listdir("/usr/share/alsa/ucm2/Intel")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/alsa/ucm2/Intel' `

**Comment by Apacelus** [comment]
@jimbobcraig which distro are you on?

**Comment by WeirdTreeThing** [comment]
I fixed the incorrect package name.

**Comment by Apacelus** [comment]
Fixed the folder not found error in https://github.com/eupnea-linux/audio-scripts/commit/f936d095f1cedcab9ae72eae7da318474ea3abf7

Fixed the firmware package error in https://github.com/eupnea-linux/audio-scripts/commit/22d6735b967533bb7c900bc6bec6b41113ba33e8

**Comment by Apacelus** [comment]
@jimbobcraig please run ``update-scripts`` and try again

**Comment by jimbobcraig** [comment]
all working now. thanks heaps for the support in getting this working. excellent responses & helping my learning @Apacelus & @WeirdTreeThing very much appreciated

> @jimbobcraig which distro are you on?

I picked Debian/Mate but only because all my previous experience had been with Raspbian. Perhaps not the best choice... ?

**Comment by Apacelus** [comment]
Yea, debian should have a warning when you select it
