### ISSUE TITLE
Audio not working on rammus (ASUS C425T, Amber Lake)

### ISSUE THREAD

**Issue by jacob019** [eupnea-linux/audio-scripts#26]
With mainline the audio device shows up, but there is no output from the speakers.  Headphones work.

**Comment by WeirdTreeThing** [comment]
Speakers are disabled for now until there is a volume limiter.

**Comment by Apacelus** [comment]
> Speakers are disabled for now until there is a volume limiter.

Does the script explicitly warn the users about that?

**Comment by WeirdTreeThing** [comment]
Yes.

**Comment by jacob019** [comment]
The warning says only "You need to have a patched kernel to have working speakers on kabylake."  I do not have kabylake.  I would like to work on the volume limiter problem.  How do I re-enable the speakers?

**Comment by WeirdTreeThing** [comment]
I group Kabylake and Amberlake together in the script and that comment is still true. If you really want speakers the instructions to enable them are in the setup-audio file but be warned that it can fry your speakers.

**Comment by jacob019** [comment]
I commented out that line and ran the script, still no audio on the speakers.  I verified that the file is present as well.  The only audio ports that show up are Line Out and Headphone.

**Comment by WeirdTreeThing** [comment]
Your device uses an incompatible speaker amp.

**Comment by jacob019** [comment]
That's a bummer.  Future support is unlikely?  Thanks.

**Comment by WeirdTreeThing** [comment]
Rammus now has support.
