### ISSUE TITLE
HDMI Audio is broken after updating kernel to 6.1

### ISSUE THREAD

**Issue by slimx** [eupnea-linux/audio-scripts#27]
cp713(i7-10510u)

there  is a bug for this:
https://bugzilla.kernel.org/show_bug.cgi?id=216836
it fixed in 6.1.3 for amd cpu,but doesn't work for intel cpu

**Comment by WeirdTreeThing** [comment]
I'm not sure how this issue is related to the script at all since this is a kernel issue.
