### ISSUE TITLE
Audio not working on HP 11 G6 EE Apollo Lake/"Snappy"

### ISSUE THREAD

**Issue by Corgi** [eupnea-linux/audio-scripts#28]
Latest Pop!_OS build, have switched the kernel to mainline, and have run `setup-audio`. Upon reboot, output is still "dummy output," with no additional outputs to switch to. I used the SOF option and have not tried AVS.

Please let me know if I can provide additional details. Thanks!

**Comment by WeirdTreeThing** [comment]
Look in your audio settings and see if there is a disabled device.

**Comment by Corgi** [comment]
> Look in your audio settings and see if there is a disabled device.

Hi,

As far as I can tell there is only the dummy output as seen below:

![IMG_2401](https://user-images.githubusercontent.com/1316783/211956672-6996d5fa-e6e5-479c-9f23-83cd32214fea.jpg)

Apologies for the phone photo, I could not figure out how to take a screenshot in pop os.

**Comment by WeirdTreeThing** [comment]
Update your system with `sudo apt update; sudo apt upgrade -y` and run `setup-audio` again.

**Comment by Corgi** [comment]
Just did so now. Still no change, only the dummy output is available.

**Comment by WeirdTreeThing** [comment]
Run `collect-logs` and upload the file it creates.

**Comment by Corgi** [comment]
Here you go:

[2023-01-12_10h-56m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10404053/2023-01-12_10h-56m-eupnea-logs.tar.gz)

Thanks for your help with this issue.

**Comment by Corgi** [comment]
No joy, here is the output of `cat /etc/modprobe.d/alsa-sof.conf`.

```
corgi@snappy:~$ cat /etc/modprobe.d/alsa-sof.conf
options snd-intel-dspcfg dsp_driver=3
blacklist snd_hda_intel
blacklist snd_soc_skl
softdep snd_sof_pci_intel_icl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_cnl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_apl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tng pre: snd_hda_codec_hdmi
```

As an aside, I've noticed that running `sudo apt update` doesn't seem to ever find anything to update from the github repo, which may be part of our problem.

**Comment by Apacelus** [comment]
What is the version of the eupnea-utils package on your system?

**Comment by Corgi** [comment]
Typing `eupnea-utils` in terminal returns command not found.

**Comment by WeirdTreeThing** [comment]
SOF speakers works on apl.
