### ISSUE TITLE
Audio not working for Asus Chromebook Flip C436FA

### ISSUE THREAD

**Issue by evlist** [eupnea-linux/audio-scripts#29]
I have installed Ubuntu 22.04 and everything is working smoothly (thanks a lot for this really nice tool) except the audio. 

setup-audio (after apt-get update/dist-upgrade) reports no error but the audio still doesn't work after reboot and the settings show only a dummy audio output.

Thanks,

Eric

**Comment by evlist** [comment]
Here come the logs... [2023-01-14_14h-46m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10417464/2023-01-14_14h-46m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Looks like I don't have UCM for that specific audio setup yet, it should be ready soon.

**Comment by evlist** [comment]
Thanks, let me know if there is anything I can do to help!

**Comment by WeirdTreeThing** [comment]
I have the UCM now. Update all your packages with your package manager and run `setup-audio` and you should have working audio. Let me know if it works or not.

**Comment by evlist** [comment]
Just did the update (and setup-audio) but the audio is still not working (gnome doesn't see other devices than the dummy one).
[2023-01-16_08h-25m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10423428/2023-01-16_08h-25m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
I made some modifications to the ucm that should fix it. Run `setup-audio` again and see if it works.

**Comment by evlist** [comment]
Nope, still no sound (after apt-get update/dist-upgrade and setup-audio) !

[2023-01-17_10h-28m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10433426/2023-01-17_10h-28m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
Can you run `alsaucm reload` and upload the output.

**Comment by evlist** [comment]
Sure:
```
vdv@helios:~$ alsaucm reload 
ALSA lib main.c:1412:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
alsaucm: error failed to open sound card hw:0: No such file or directory
```

**Comment by WeirdTreeThing** [comment]
That is weird, can you install strace and run `strace alsaucm reload > alsaucm.log 2>&1` and upload the output

**Comment by evlist** [comment]
Here it is:
[alsaucm.log](https://github.com/eupnea-linux/audio-scripts/files/10438138/alsaucm.log)

**Comment by evlist** [comment]
Just tried again with a video projector connected via HDMI and the audio doesn't work either...

Is there anything I can do ?

Thanks,

Eric

**Comment by WeirdTreeThing** [comment]
So none of your audio works at all?

**Comment by evlist** [comment]
No, I just get the dummy audio listed as a device !

**Comment by WeirdTreeThing** [comment]
Run `collect-logs` and upload the file it creates here.

**Comment by evlist** [comment]
Here it is:
[2023-01-30_16h-49m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10537354/2023-01-30_16h-49m-eupnea-logs.tar.gz)

**Comment by evlist** [comment]
Yep ! [alsaucm.log](https://github.com/eupnea-linux/audio-scripts/files/10539029/alsaucm.log)

**Comment by psipika** [comment]
@evlist what does your `lspci` report as the sound device? ...just curious of it's the same as a C425...

**Comment by evlist** [comment]
@psipika:
```
00:1f.3 Multimedia audio controller: Intel Corporation Comet Lake PCH-LP cAVS
	DeviceName: Multimedia audio controller
	Subsystem: Intel Corporation Comet Lake PCH-LP cAVS
	Flags: bus master, fast devsel, latency 64, IRQ 149, IOMMU group 12
	Memory at d1214000 (64-bit, non-prefetchable) [size=16K]
	Memory at d1100000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [50] Power Management version 3
	Capabilities: [80] Vendor Specific Information: Len=14 <?>
	Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Kernel driver in use: sof-audio-pci-intel-cnl
	Kernel modules: snd_hda_intel, snd_soc_skl, snd_sof_pci_intel_cnl
```

**Comment by WeirdTreeThing** [comment]
@evlist I pushed a fix but most likely the package has not been rebuilt, you will need to clone this repo instead.

**Comment by WeirdTreeThing** [comment]
@psipika Each generation has a different pci audio device. So the one for cometlake will be different than the one for kabylake and so on.

**Comment by evlist** [comment]
Yep ! [alsaucm.log](https://github.com/eupnea-linux/audio-scripts/files/10539029/alsaucm.log)

**Comment by evlist** [comment]
Just tried again with a cloned repo and I have the same problem. Here are the logs and strace.

[2023-02-04_11h-50m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10608426/2023-02-04_11h-50m-eupnea-logs.tar.gz)
[alsaucm.log](https://github.com/eupnea-linux/audio-scripts/files/10608435/alsaucm.log)

**Comment by evlist** [comment]
I can switch to 22.10, can I just use Ubuntu's upgrade-manager or would that break the Depthboot image ?

**Comment by Apacelus** [comment]
I dont think the upgrade manager should break anything, but I havent tested it either.

**Comment by evlist** [comment]
I can confirm that the audio is working with 22.10 (and also that the upgrade manager doesn't break anything).

Many thanks for your help and also for the Eupnea project in general.

**Comment by WeirdTreeThing** [comment]
Great to see that audio is working.
