### ISSUE TITLE
How do I revert the changes that these scripts make?

### ISSUE THREAD

**Issue by TheoCGaming** [eupnea-linux/audio-scripts#30]
I installed this on a chromebook running off of a USB stick with an installation of Arch Linux on it. The USB stick is now in another computer that is running off of it, and the audio is stuck on "Dummy Output". How do I revert the changes the audio scripts made so that audio works again?

**Comment by WeirdTreeThing** [comment]
Delete any file in /etc/modprobe.d/

**Comment by TheoCGaming** [comment]
it worked, thanks!
