### ISSUE TITLE
Audio not working on Acer Chromebook Spin 511 R753TN-C6NQ

### ISSUE THREAD

**Issue by kolAflash** [eupnea-linux/audio-scripts#32]
There's nothing to hear (sound isn't working). Neither with internal speakers, not with external headphones. Also no microphone device seems to be detected.

**At first: Thanks a lot for the great work!**

&nbsp;

Device: Acer Chromebook Spin 511 R753TN-C6NQ  
https://geizhals.de/acer-chromebook-spin-511-r752tn-c07t-nx-hpxeg-002-a2256776.html  
I'm using a freshly set up USB storage with Ubuntu-22.04 and mainline kernel (6.0.9).

`pavucontrol` shows `sof-rt5682`. Headphones are being detected (if plugged in), but there's no sound.  
`sof-rt5682` has only `Stereo Output`. No microphone device is being detected.
`collect-logs`: [2023-02-04_13h-49m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10608856/2023-02-04_13h-49m-eupnea-logs.tar.gz)

&nbsp;

`/etc/modprobe.d/alsa-sof.conf`:
```
options snd-intel-dspcfg dsp_driver=3
blacklist snd_hda_intel
blacklist snd_soc_skl
softdep snd_sof_pci_intel_icl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_cnl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_apl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_hdmi
softdep snd_sof_pci_intel_tng pre: snd_hda_codec_hdmi
```

&nbsp;

`apt remove firmware-sof-signed && apt install firmware-sof-signed` didn't help.

&nbsp;

&nbsp;

P.S.

I tried checking the settings in alsamixer. But I couldn't switch soundcards (F6 hotkey in alsamixer), because I don't know how to use function keys. Even the function keys of an external usb keyboard where detected as make screenshow, lower/raise brightness, lower/raise volume, ...

And the touchscreen isn't working at all. It's just a display, no touch input possible. Can you give me a hint where to continue digging or where to open an issue for this?

&nbsp;

----

&nbsp;

_Supplement (2023-02-04 16:52 UTC+1)_
_OS: Ubuntu-22.04_
_Kernel: mainline 6.0.9_

**Comment by Apacelus** [comment]
Touchscreen is a known issue and we are in the process of fixing it. Switch to the chromeos kernel for now(`manage-kernels -u --stable`.

Ubuntu 22.04 is currently a bit "broken" and will be fixed soon. Either wait a few weeks or use Ubuntu 22.10/any other distro

**Comment by kolAflash** [comment]
@Apacelus  
Now trying Ubuntu-22.10 and stable (magolor) kernel 5.10.133.  
After running `setup-audio` the audio output works via headphone, but not via internal speakers.
  
`pavucontrol` shows `Jasper Lake HD Audio` which is enabled (set to `Default`) and has three output devices
- `Jasper Lake HD Audio HMDI / DisplayPort Output` (didn't test)
- `Jasper Lake HD Audio Headphones` (working and headphones are detected on plugin)
- `Jasper Lake HD Audio Speaker` (no sound)
and two input devices
- `Jasper Lake HD Audio Internal Microphone` (tested, working)
- `Jasper Lake HD Audio Headset Microphone` (tested, working)

collect-logs: [2023-02-04_16h-07m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10609047/2023-02-04_16h-07m-eupnea-logs.tar.gz)  
`/etc/modprobe.d/alsa-sof.conf` is the same as above.

&nbsp;

&nbsp;

Touchscreen works now too. Thanks!

But one more thing:  
I don't know how to switch to the backside webcam (it's above the keyboard). There's `/dev/video0` and `/dev/video1`. But for example in Firefox running [Jitsi-Meet](https://en.wikipedia.org/wiki/Jitsi#Jitsi_Meet) I can only select the frontside webcam (above the display). I also couldn't switch webcams with Ubuntu-22.04 and mainline 6.0.9 kernel before switching to Ubuntu-22.10 and stable (magolor) kernel 5.10.133.

**Comment by Apacelus** [comment]
How did you switch the webcam in chromeos? Or were there just 2 webcams available?

**Comment by kolAflash** [comment]
@Apacelus  
> How did you switch the webcam in chromeos? Or were there just 2 webcams available?

Good question. I didn't use ChromeOS 😅  
Bought that notebook because I thought it would be a nice and cheap Linux system 😁

But I just tested it:  
I can simply select the other webcam inside applications. Same as if you connect 2 USB webcams to a computer.  
In `/dev/` there are 15 video devices. `video0` up to `video14`.

```
localhost ~ # lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0026 Intel Corp. 
Bus 001 Device 002: ID 04f2:b71b Chicony Electronics Co., Ltd HD User Facing
Bus 001 Device 006: ID 0fe6:9900 Kontron (Industrial Computer Source / ICS Advent) 10/100M LAN
Bus 001 Device 005: ID 0639:7210 Chrontel, Inc. Billboard
Bus 001 Device 004: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
localhost ~ # lspci 
00:00.0 Host bridge: Intel Corporation Device 4e12
00:02.0 VGA compatible controller: Intel Corporation JasperLake [UHD Graphics] (rev 01)
00:04.0 Signal processing controller: Intel Corporation Dynamic Tuning service
00:05.0 Multimedia controller: Intel Corporation JasperLake IPU
00:08.0 System peripheral: Intel Corporation Device 4e11
00:14.0 USB controller: Intel Corporation Device 4ded (rev 01)
00:14.2 RAM memory: Intel Corporation Device 4def (rev 01)
00:14.3 Network controller: Intel Corporation Wi-Fi 6 AX201 160MHz (rev 01)
00:14.5 SD Host controller: Intel Corporation Device 4df8 (rev 01)
00:15.0 Serial bus controller: Intel Corporation Serial IO I2C Host Controller (rev 01)
00:15.1 Serial bus controller: Intel Corporation Serial IO I2C Host Controller (rev 01)
00:15.2 Serial bus controller: Intel Corporation Device 4dea (rev 01)
00:15.3 Serial bus controller: Intel Corporation Device 4deb (rev 01)
00:16.0 Communication controller: Intel Corporation Management Engine Interface (rev 01)
00:19.0 Serial bus controller: Intel Corporation Device 4dc5 (rev 01)
00:19.2 Communication controller: Intel Corporation Device 4dc7 (rev 01)
00:1a.0 SD Host controller: Intel Corporation Device 4dc4 (rev 01)
00:1e.0 Communication controller: Intel Corporation Device 4da8 (rev 01)
00:1e.2 Serial bus controller: Intel Corporation Device 4daa (rev 01)
00:1f.0 ISA bridge: Intel Corporation Device 4d87 (rev 01)
00:1f.3 Multimedia audio controller: Intel Corporation Jasper Lake HD Audio (rev 01)
00:1f.5 Serial bus controller: Intel Corporation Jasper Lake SPI Controller (rev 01)
localhost ~ # ls -lAhs /sys/class/video4linux/
total 0
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev0 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev0
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev1 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev1
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev10 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev10
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev11 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev11
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev12 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev12
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev13 -> ../../devices/pci0000:00/0000:00:15.3/i2c_designware.3/i2c-15/i2c-OVTI5675:00/video4linux/v4l-subdev13
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev14 -> ../../devices/pci0000:00/0000:00:15.3/i2c_designware.3/i2c-15/i2c-PRP0001:01/video4linux/v4l-subdev14
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev2 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev2
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev3 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev3
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev4 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev4
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev5 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev5
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev6 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev6
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev7 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev7
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev8 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev8
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 v4l-subdev9 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/v4l-subdev9
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video0 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video0
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video1 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video1
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video10 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video10
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video11 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video11
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video12 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video12
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video13 -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/video4linux/video13
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video14 -> ../../devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/video4linux/video14
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video2 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video2
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video3 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video3
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video4 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video4
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video5 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video5
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video6 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video6
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video7 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video7
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video8 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video8
0 lrwxrwxrwx. 1 root root 0 Feb  4 17:26 video9 -> ../../devices/pci0000:00/0000:00:05.0/intel-ipu6-isys0/video4linux/video9
```

**Comment by Apacelus** [comment]
@kolAflash the logs are from ChromeOS, right?

Also, this may be fixed in the newer kernels, which will soon be pushed to all Depthboot devices.

**Comment by kolAflash** [comment]
@Apacelus Yes, the logs are from ChromeOS.

**Comment by kolAflash** [comment]
@Apacelus

If you like to have a chat (and maybe remote control the system) just send me a mail with your contact.  
(Jabber/XMPP, Matrix/Element, Threema, wire.im, Skype, ...)

kolAflash AT kolahilft.de

**Comment by Apacelus** [comment]
@kolAflash we have a pretty big discord, maybe you could join us there?

**Comment by kolAflash** [comment]
@Apacelus  
Sure. I just send you a friend request in Discord.

**Comment by kolAflash** [comment]
@Apacelus Did you get my friend request in Discord? My Discord ID is kolAflash#5793

**Comment by kolAflash** [comment]
**for the record**

Moved discussion here:
https://discord.com/channels/994245999822381076/1071479424731594792/1071479424731594792

**Comment by WeirdTreeThing** [comment]
Closing as this has gone off topic from audio.
