### ISSUE TITLE
No sound on my hp chromebook 14 g5 (apollo lake)

### ISSUE THREAD

**Issue by foxrus** [eupnea-linux/audio-scripts#33]
Hi, I tried your system but there is no sound on my chromebook.
When I boot my original chrome os, it shows this 
`chronos@localhost / $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: avsmax98357a [avs_max98357a], device 1: Built-in Speakers (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: avsda7219 [avs_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: hdaudioB0D2 [hdaudioB0D2], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

But when I download your build, there is no sound at all

**Comment by foxrus** [comment]
I also ran your script, but when I run sof, even the sound setting disappears. And when I run avs there is no sound either

**Comment by foxrus** [comment]
In Ubuntu 22.10, after installing avs, the sound appears in the configuration menu as headphones, but there is no sound from the speakers. 
Here is the output of aplay
`fox@snappy:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: avsda7219 [avs_da7219], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

**Comment by WeirdTreeThing** [comment]
Not sure why sof isn't working, I will have to test that out. Speakers are disabled on AVS to prevent damage to them, if you want there is a workaround but be warned that it can permanently damage your speakers.

**Comment by WeirdTreeThing** [comment]
Also seems like I broke HDMI audio.

**Comment by foxrus** [comment]
No more options?

**Comment by foxrus** [comment]
Why doesn't avsmax98357a work? As in the original chrome os?

**Comment by foxrus** [comment]
I've seen closed issues where you've been very good at helping people. Could you please help me too?

**Comment by WeirdTreeThing** [comment]
Everything works as intended, not a real issue.

**Comment by Apacelus** [comment]
@foxrus please update your local clone (`git pull`) and rerun the script

**Comment by foxrus** [comment]
> please update your local clone (`git pull`) and rerun the script

Nothing happens, there is no sound, and there is no sound.

**Comment by foxrus** [comment]
> Everything works as intended, not a real issue.

Why did you close the thread, because I never got the sound?

**Comment by Apacelus** [comment]
Did you run the script from a fresh clone? Did the script make you type something out?

**Comment by foxrus** [comment]
> Did you run the script from a fresh clone? Did the script make you type something out?

That's what I wrote - I Understand my speakers will not work!
But after rebooting the system, I still didn't get the sound

**Comment by WeirdTreeThing** [comment]
PEBKAC moment.

**Comment by Apacelus** [comment]
@foxrus I have updated the script and added an override option if you want to blow up your speakers. 

Just a reminder, this project is licensed under GPLv3 ([license](https://github.com/eupnea-linux/audio-scripts/blob/main/LICENSE)). Here is a part of that license:
>   16. Limitation of Liability.
>
> IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.

**Comment by foxrus** [comment]
> @foxrus I have updated the script and added an override option if you want to blow up your speakers.
> 
> Just a reminder, this project is licensed under GPLv3 ([license](https://github.com/eupnea-linux/audio-scripts/blob/main/LICENSE)). Here is a part of that license:
> 
> > 16. Limitation of Liability.
> > 
> > IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
> > WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
> > THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
> > GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
> > USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
> > DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
> > PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
> > EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
> > SUCH DAMAGES.

But there is still no sound

**Comment by Apacelus** [comment]
@foxrus have you tried running the script with the override flag?

**Comment by foxrus** [comment]
> 

What is this flag?

**Comment by Apacelus** [comment]
Get a fresh script clone, run it and the script will tell you

**Comment by foxrus** [comment]
> Get a fresh script clone, run it and the script will tell you

This time it asked me to print - I understand the risk of permanently damaging my speakers, but after rebooting I still have no sound

**Comment by Apacelus** [comment]
@foxrus AVS is very unstable and even causes PERMANENT damage to speakers. The script gave multiple warnings about that.

Or are you talking about aux/headphones sound not working?

**Comment by foxrus** [comment]
> @foxrus AVS is very unstable and even causes PERMANENT damage to speakers. The script gave multiple warnings about that.
> 
> Or are you talking about aux/headphones sound not working?

I managed to adjust the sound, I had to switch the option from headphones to speakers in the settings, and the sound worked fine.
It just doesn't work very well, and if you set the sound to more than 75%, the speakers start to wheeze. Is there any way to fix this?

**Comment by foxrus** [comment]
Is there any way to limit it?

**Comment by Apacelus** [comment]
@foxrus if you increase the sound even further your speakers will **BLOW UP!!!**

**Comment by Apacelus** [comment]
There is no way to cap the volume at the moment, which is the reason for the warnings in the script

**Comment by foxrus** [comment]
If there was some way to limit this, it would help a lot of people.

**Comment by foxrus** [comment]
Thank you very much for your help. I will be following your work.

**Comment by Apacelus** [comment]
@foxrus If you find one, you are free to submit a pr. Neither we, nor the Chrultrabook community have found one yet.
