### ISSUE TITLE
Audio not working on Asus Chromebook Flip C204 (Arch)

### ISSUE THREAD

**Issue by nicco1690** [eupnea-linux/audio-scripts#35]
After running `setup-audio` and rebooting, audio is still not recognized by XFCE, or any other program for that matter. When running `collect-logs`, it reports that PulseAudio is not installed.
[2023-02-18_16h-33m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10775246/2023-02-18_16h-33m-eupnea-logs.tar.gz)

**Comment by nicco1690** [comment]
But when opening Furnace, the internal speakers work just fine... I don't really know what's going on. But it still also doesn't let me change the volume using the buttons on the keyboard.

**Comment by Apacelus** [comment]
> But it still also doesn't let me change the volume using the buttons on the keyboard.
XFCE issue, I am not able to do that on my Chromebook under XFCE either

**Comment by WeirdTreeThing** [comment]
Your issue seems to be that you don't have any audio server installed.

**Comment by Apacelus** [comment]
Fixed the audio issue for new Depthboot installs in https://github.com/eupnea-linux/depthboot-builder/commit/8dbfb127ace7fd8f5f5aa898a386cc4aca446aaf
