### ISSUE TITLE
ZorinOS Support?

### ISSUE THREAD

**Issue by SteadyStatus21** [eupnea-linux/audio-scripts#36]
Hello! 
I am having issues trying to install this on my ZorinOS System. What might be different from Ubuntu that would make it not want to install?
If anyone has any ideas, I am down to try them. 

Thanks!
-Steady

**Comment by Apacelus** [comment]
What issues are you having... Can you show some logs

**Comment by SteadyStatus21** [comment]
Sorry for the delay... Just got your response via email. 
Here is what I get when attempting to run the script:
```
  File "./setup-audio", line 145
    match platform:
          ^
SyntaxError: invalid syntax
```

**Comment by SteadyStatus21** [comment]
Update: I realized Python 3.10 was required. Now this is the log with Python 3.10:
```
steadystatus21@steadystatus21-ultrabook:~/audio-scripts$ python3.10 ./setup-audio 
Couldn't remove non existent directory: /tmp/eupnea-audio, ignoring
WARNING: this audio script is not fully functional yet!
Installing SOF
E: Unable to locate package firmware-sof-signed
Traceback (most recent call last):
  File "/home/steadystatus21/audio-scripts/./setup-audio", line 378, in <module>
    sof_audio("glk")
  File "/home/steadystatus21/audio-scripts/./setup-audio", line 127, in sof_audio
    install_package("sof-firmware", "firmware-sof-signed", "alsa-sof-firmware", "sof-firmware", "sof-firmware",
  File "/home/steadystatus21/audio-scripts/./setup-audio", line 265, in install_package
    bash(f"apt-get install -y --reinstall {deb_package}")
  File "/home/steadystatus21/audio-scripts/functions.py", line 119, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'apt-get install -y --reinstall firmware-sof-signed' returned non-zero exit status 100.
steadystatus21@steadystatus21-ultrabook:~/audio-scripts$ 
```

**Comment by Apacelus** [comment]
ZorinOS is based on Ubuntu 20.04, which is way too old for our script

**Comment by SteadyStatus21** [comment]
> ZorinOS is based on Ubuntu 20.04, which is way too old for our script

So, is there a way to manually install these drivers, and if so, how could I try?

**Comment by Apacelus** [comment]
Its a dependency hell type of situation. You would need backported packages, which probably rely on newer packages of core system parts, so its more or less impossible

**Comment by SteadyStatus21** [comment]
> Its a dependency hell type of situation. You would need backported packages, which probably rely on newer packages of core system parts, so its more or less impossible

Ah, now I understand. Thank you for helping me! Have a great rest of your day/evening!
