### ISSUE TITLE
Acer R751T(Apollo Lake) doesn't suspend after AVS install

### ISSUE THREAD

**Issue by BlomborYum** [eupnea-linux/audio-scripts#37]
After pressing the power button, which is set to suspend the laptop, the system resets and the white chromeos screen appears. 

This happens on Ubuntu 22.10 + gnome and on Arch + gnome(mainline kernel, booted from a pendrive). Both systems had installed the AVS sound driver with '--force-avs-install' flag.

I think it might be related to the sound driver because before installing it, the suspend option worked.

**Comment by Apacelus** [comment]
Are you using Depthboot? Are you sure this does not happen if you dont install audio?

**Comment by WeirdTreeThing** [comment]
What kernel version are you on?

**Comment by BlomborYum** [comment]
@Apacelus 
1. I'm using Depthboot, if by that you mean unmodified chromebook firmware.
2. After some testing, I don't think its a problem with the sound driver afterall. I've just gotten luck the several times I suspended the laptop before the driver install and unluck just after installing it. The problem seems to be intermittent and I was able to suspend a couple times with the driver installed.

@WeirdTreeThing  Kernel: 6.2.1-eupnea. 

I've also got an older pendrive with Arch/lxqt/avs-driver that doesn't have this suspend problem. I'll check its kernel version in a moment.

**Comment by Apacelus** [comment]
If you encounter this problem again, please open an issue in the Depthboot repo or the appropriate kernel repo. (Or on Discord)

**Comment by BlomborYum** [comment]
@Apacelus Just encountered the bug again after letting the laptop sit idle for a few minutes and then suspending. I'll open an issue in the depthboot repo, this one can be closed.

**Comment by WeirdTreeThing** [comment]
I'll test this on my system.
