### ISSUE TITLE
HP Chromebook C640 G2 - no sound, even after install on system

### ISSUE THREAD

**Issue by nobrainer-de** [eupnea-linux/audio-scripts#38]
Hi there,
i installed freshly Pop OS on my HP Chromebook c640 G2 and installed audio with `setup-audio` but it wont work.

Here is my collect-logs
[2023-03-02_20h-27m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/10875162/2023-03-02_20h-27m-eupnea-logs.tar.gz)

eupnea-utils returns "`command not found`".

> XXX@elemi:~$ cat /etc/modprobe.d/alsa-sof.conf
> options snd-intel-dspcfg dsp_driver=3
> blacklist snd_hda_intel
> blacklist snd_soc_skl
> softdep snd_sof_pci_intel_icl pre: snd_hda_codec_hdmi
> softdep snd_sof_pci_intel_cnl pre: snd_hda_codec_hdmi
> softdep snd_sof_pci_intel_apl pre: snd_hda_codec_hdmi
> softdep snd_sof_pci_intel_tgl pre: snd_hda_codec_hdmi
> softdep snd_sof_pci_intel_tng pre: snd_hda_codec_hdmi

System is up2date.

any idea? something i can try?

**Comment by WeirdTreeThing** [comment]
Looks like there are two issues. The first is a kernel issue which will get sorted out in the next few days, the other is your device needs UCM which I haven't created yet but I can do soon.

**Comment by WeirdTreeThing** [comment]
@nobrainer-de sorry for the wait but I added UCM for your device.

**Comment by WeirdTreeThing** [comment]
If it still doesn't work feel free to reopen the issue.

**Comment by nobrainer-de** [comment]
Hey @WeirdTreeThing still no functionality sadly.

xxx@elemi:~$ cat /etc/modprobe.d/alsa-sof-conf
options snd-intel-dspcfg dsp_driver=3
