### ISSUE TITLE
Pixelbook Eve, no audio, kernel panic on shutdown/reboot

### ISSUE THREAD

**Issue by jmontleon** [eupnea-linux/audio-scripts#39]
Right up front, I'll admit I did not use the script. I am interested in making a package to get AVS working for
https://github.com/jmontleon/pixelbook-fedora, and so was trying to step through what files need to go where to get the kblr55145663max working.

Do I need `intel/avs/hda-8086280b-tplg.bin`? It doesn't look like it's in this repo. 

I have `/lib/firmware/intel/avs/max98927-tplg.bin` and `/lib/firmware/intel/avs/skl/dsp_basefw.bin` in place, but it doesn't look to be loading properly.

```
[    8.426253] snd_soc_avs 0000:00:1f.3: Direct firmware load for intel/avs/hda-8086280b-tplg.bin failed with error -2
[    8.426259] snd_soc_avs 0000:00:1f.3: request topology "intel/avs/hda-8086280b-tplg.bin" failed: -2
[    8.426264] snd_soc_avs 0000:00:1f.3: ASoC: error at snd_soc_component_probe on hdaudioB0D2-platform: -2
[    8.426299] avs_hdaudio avs_hdaudio.2: ASoC: failed to instantiate card -2
[    8.426451] avs_hdaudio: probe of avs_hdaudio.2 failed with error -2
[    8.436085] avs_max98927 avs_max98927.1: ASoC: no complete control IO handler for DSM data type (g,p,i) 0:0:5 at 0xa3c
[    8.436094] avs_max98927 avs_max98927.1: ASoC: invalid control
[    8.436097] avs_max98927 avs_max98927.1: ASoC: topology: could not load header: -22
[    8.436102] snd_soc_avs 0000:00:1f.3: load topology "intel/avs/max98927-tplg.bin" failed: -22
[    8.436110] snd_soc_avs 0000:00:1f.3: ASoC: error at snd_soc_component_probe on avs_max98927.1-platform: -22
[    8.436129] avs_max98927 avs_max98927.1: ASoC: failed to instantiate card -22
[    8.436174] avs_max98927: probe of avs_max98927.1 failed with error -22
```

**Comment by jmontleon** [comment]
This panic happens when shutting down with AVS enabled.

![PXL_20230307_224330940](https://user-images.githubusercontent.com/1850500/223572297-d7d5d9bf-e204-4739-8c21-bb12d2289cb7.jpg)

**Comment by WeirdTreeThing** [comment]
> and so was trying to step through what files need to go where to get the kblr55145663max working.

Unfortunately the pixelbook's complicated audio setup doesn't work too well with AVS yet. max98927 for the speakers does work in mainline-ish linux. rt5662 for the headphone jack does have a machine driver thanks to [this patch](https://patchwork.kernel.org/project/alsa-devel/patch/Y6No3WsiZ7Sbg35u@tora/) but we currently don't have a topology which makes it useless. rt5514 for the internal mic has no support at all yet.

> Do I need intel/avs/hda-8086280b-tplg.bin? It doesn't look like it's in this repo.

There are a few different configurations for HDMI audio and it looks like I just missed that one, yes you do need it for HDMI audio.

> avs_max98927 avs_max98927.1: ASoC: no complete control IO handler for DSM data type (g,p,i) 0:0:5 at 0xa3c

Back to the mainline-ish kernel, you will need to backport the [DSP volume controls series](https://patchwork.kernel.org/project/alsa-devel/list/?series=704452&state=%2A&archive=both) that is currently in linux-next, these patches and more for the AVS driver should be merged into stable within the next few weeks. The topology currently in the repo will only work on the ChromeOS kernel, so you will need to compile it yourself from [here](https://github.com/thesofproject/avs-topology-xml/blob/aslawinx/max98927/i2s/max98927-tplg.xml) until I update the topology to be the one from upstream.

About that kernel error you got, it seems like there is a bug in stable 6.2 that makes the AVS driver very unstable, I still need to test a few versions to see where it broke but either [6.2-rc8](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/?h=v6.2-rc8) or [6.2](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/?h=v6.2) from the mainline branch should work.

**Comment by jmontleon** [comment]
Thank you for the quick response and explanation! That gives me some things to play around with when I have some time. Much appreciated!

**Comment by WeirdTreeThing** [comment]
@jmontleon if you still need help feel free to reopen the issue.
