### ISSUE TITLE
Extremely choppy audio on Braswell

### ISSUE THREAD

**Issue by Metal-Toilet** [eupnea-linux/audio-scripts#4]
When booted into Debian Gnome on my Acer R11 (CYAN) (A Braswell device) my audio is extremely choppy. Its especially bad in youtube (video choppy too) but is bad everywhere I tested. I have not ran any setup scripts on Apacelus's advice. Any help is much appreciated.

**Comment by WeirdTreeThing** [comment]
Braswell shouldn't need to use this script as support is in any mainline distro.

**Comment by Apacelus** [comment]
It seems mainline support isnt perfect. Keep this issue open until we can find a definitive solution for it

**Comment by WeirdTreeThing** [comment]
It worked just fine on my BANON.

**Comment by Metal-Toilet** [comment]
Audio support started to work fine after connecting to Bluetooth headphones and disconnecting. Sometimes it will break again but it is quickly fixed by using Bluetooth.
