### ISSUE TITLE
No audio on Debian Bookworm/XFCE

### ISSUE THREAD

**Issue by Dggrr** [eupnea-linux/audio-scripts#44]
I've installed Debian 12 Bookworm with XFCE on my Asus Flip C302CA (Cave/Skylake motherboard). and then run the setup_audio script but still only see a Dummy output device.

There are no obvious firmware errors in dmesg or journalctl -b.

There are too many snd modules loaded!   File attached - [snd_modules.txt](https://github.com/eupnea-linux/audio-scripts/files/11091955/snd_modules.txt).

What to do next?

**Comment by WeirdTreeThing** [comment]
The default debian kernel doesn't support AVS. You either need to compile your own kernel with AVS or use the eupnea mainline kernel.

**Comment by Dggrr** [comment]
OK, thanks.  I'll work on that

**Comment by Dggrr** [comment]
Yes, that fixed it.  I'm now running an 6.2.8 kernel with the AVS modules and have HDMI and headphone audio.

I do see the following dmesg at the end of boot but pipewire/alsa audio seems to be working:

[   27.495094] CPU: 0 PID: 803 Comm: wireplumber Not tainted 6.2.8 #2
[   27.495099] Hardware name: Google Cave/Cave, BIOS MrChromebox-4.19.1 01/29/2023
[   27.495101] RIP: 0010:avs_copier_create+0x2ff/0x340 [snd_soc_avs]
[   27.495126] Code: fe ff ff b9 04 00 00 00 4c 89 fe 48 c7 c2 d0 2d 88 c1 48 c7 c7 10 2e 88 c1 48 89 44 24 08 c6 05 10 a4 01 00 01 e8 c1 93 03 cb <0f> 0b 48 8b 44 24 08 e9 34 fe ff ff 49 8b bd 90 05 00 00 48 c7 c6
[   27.495130] RSP: 0018:ffffaab5410d35b0 EFLAGS: 00010286
[   27.495135] RAX: 0000000000000000 RBX: ffff99514666ad80 RCX: 0000000000000000
[   27.495138] RDX: 0000000000000002 RSI: ffffffff8da57e19 RDI: 00000000ffffffff
[   27.495142] RBP: ffff995161d96028 R08: 0000000000000000 R09: ffffaab5410d3440
[   27.495145] R10: 0000000000000003 R11: ffffffff8e6d16a8 R12: ffff9951456bea00
[   27.495148] R13: ffff995144a2e828 R14: 00000000000000a4 R15: 0000000000000054
[   27.495151] FS:  00007f4923e9f840(0000) GS:ffff9951bac00000(0000) knlGS:0000000000000000
[   27.495169] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   27.495173] CR2: 00007fe468025000 CR3: 0000000106b06005 CR4: 00000000003706f0
[   27.495176] Call Trace:
[   27.495180]  <TASK>
[   27.495186]  avs_path_create+0x2fa/0xb80 [snd_soc_avs]
[   27.495210]  ? _regmap_update_bits+0xe0/0xf0
[   27.495220]  avs_dai_hw_params+0x5b/0x260 [snd_soc_avs]
[   27.495245]  snd_soc_dai_hw_params+0x32/0x90 [snd_soc_core]
........

**Comment by WeirdTreeThing** [comment]
There is not much we can do about that error until intel fixes it.
