### ISSUE TITLE
No support for Dell Chromebook 11 3120 (Candy)

### ISSUE THREAD

**Issue by vopey** [eupnea-linux/audio-scripts#45]
Setting up audio with `./setup-audio` on the Dell Chromebook 11 3120 (Candy) running Arch ends with the error:
`Unknown/Unsupported chromebook model: candy`

**Comment by WeirdTreeThing** [comment]
I just added baytrail support, `git pull` and try again.

**Comment by vopey** [comment]
No change in audio problems (Certain programs muting all system audio, ALSA stuck at 22%) despite the successful audio fix message and reboot.

**Comment by WeirdTreeThing** [comment]
This sounds like a problem with your audio setup/server that you are using.
