### ISSUE TITLE
Unknown/Unsupported chromebook model: coral

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/audio-scripts#47]
Device: Lenovo 500e
robo360
Apollo Lake

```
rajas@coral:~$ setup-audio
Couldn't remove non existent directory: /tmp/eupnea-audio, ignoring
WARNING: this audio script is not fully functional yet!
Unknown/Unsupported chromebook model: coral
```

My guesses on why:
- Temporarily disabled as the audio scripts are being developed
- Bug
- Not going to support this device ever

Related to #41

**Comment by WeirdTreeThing** [comment]
@ChocolateLoverRaj update your system and try again.

**Comment by WeirdTreeThing** [comment]
Run `collect-logs`.

**Comment by ChocolateLoverRaj** [comment]
I think this issue can be closed since it no longer data unknown/unsupported. Also, i set up the audio manually so maybe that would make the logs different. If you still want me to run `collect-logs` I can

**Comment by WeirdTreeThing** [comment]
Oh ok I'll just close it then.
