### ISSUE TITLE
No support for audio on Stoney Ridge

### ISSUE THREAD

**Issue by KSPAtlas** [eupnea-linux/audio-scripts#48]
**Describe the bug**
Both `setup-audio` and the build guide both correctly say audio is not suppported. I may test drivers and such on my device in order to help development.

**Device (please complete the following information):**
 - Distro [e.g. Fedora, Ubuntu]: Fedora
 - DE [e.g. gnome, kde]: GNOME
 - Version [e.g. 22.04]: 37
 - Device codename [Find it on the developer screen]: CAREENA
 - Running EupneaOS/Depthboot [yes/no]: yes

**logs**

`collect-logs` failed attempting to log (probably due to lack of audio driver).

**Comment by WeirdTreeThing** [comment]
Not even AMD cares enough to fix ACP.
