### ISSUE TITLE
How to deal with "Speakers are disabled on AVS as a safety precaution"?

### ISSUE THREAD

**Issue by sdaau** [eupnea-linux/audio-scripts#49]
**Describe the bug**

Not really a bug - just a question. First of all, thank you for the depthboot builder - I managed to start up Ubuntu 22.04 on USB key with Mate Desktop, it is great!

Following the instructions, I tried `setup-audio` - and it told me this:

```
$ setup-audio 
Couldn't remove non existent directory: /tmp/eupnea-audio, ignoring
WARNING: this audio script is not fully functional yet!
Apollolake has two audio drivers:
SOF: Stable but doesn't work with headphones or mic.
AVS: Unstable and can cause damage to speakers but supports all audio hardware.
NOTE: Speakers are disabled on AVS as a safety precaution. Your speakers will still work on SOF though.
Which driver would you like to use? [sof/avs]: ^C...KeyboardInterrupt
```

So, I decided to go with AVS, because I need headphones; after reboot of Ubuntu from USB flash, I tested sound with Audacity and headphones; note that only the `avs_da7219` devices work (both for microphone capture, and for headphone playback).

![Screenshot from 2023-04-08 16-32-50](https://user-images.githubusercontent.com/26737749/230726980-d9df81ed-f77f-439c-aaa9-0af0c27f8f97.png)

So, now the only problem is that "speakers are disabled". I understand the risks, and I usually do not use speakers, but I'd like to know - is it possible to temporarily enable them with this setup, and use them, then disable them back again? How would I do that?

**Device (please complete the following information):**
 - Distro: Ubuntu
 - DE: Mate/lightdm
 - Version: 22.04
 - Device codename: rabbid (coral)
 - Running EupneaOS/Depthboot: yes (depthboot booted from USB thumbdrive, but not installed internally yet)

**logs**

(note: you've got a typo in your github instructions: it is `collect-logs`, not `collectl-logs`)

[2023-04-08_16h-41m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/11183504/2023-04-08_16h-41m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
You can run `setup-audio --force-avs-install` to "enable" the speakers.

**Comment by Apacelus** [comment]
Add override message (even though its printed again in the avs install itself): 0d7e4e23cfd1b0193b5abaa857cc92be4bf64cfd
