### ISSUE TITLE
Lenovo 300e Gen 3 (vilboz)

### ISSUE THREAD

**Issue by mmccall0813** [eupnea-linux/audio-scripts#53]
**Describe the bug**
Unknown/unsupported board

**Device (please complete the following information):**
 - Distro [e.g. Fedora, Ubuntu]: Ubuntu
 - DE [e.g. gnome, kde]: gnome
 - Version [e.g. 22.04]: 22.04
 - Device codename [Find it on the developer screen]: vilboz
 - Running EupneaOS/Depthboot [yes/no]: yes

**logs**
[logs](https://github.com/eupnea-linux/audio-scripts/files/11289196/2023-04-20_14h-03m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
I just added the jelboz board, wait about 10 hours for the packages to be rebuilt and then update your system.

**Comment by mmccall0813** [comment]
Hmm, I ran the setup audio script and rebooted, but theres no outputs or inputs, other than "Analog Output" which doesn't do anything.

**Comment by WeirdTreeThing** [comment]
`collect-logs`

**Comment by mmccall0813** [comment]
[logs](https://cdn.discordapp.com/attachments/970739011972923422/1099034578741625013/2023-04-21_14h-09m-eupnea-logs.tar.gz)

**Comment by WeirdTreeThing** [comment]
`strace alsaucm reload -c hw:acp3xalc5682101 > strace.log 2>&1`

**Comment by WeirdTreeThing** [comment]
Ok UCM is added, you will either have to wait for the packages to rebuild again or git clone this repo and run `./setup-audio`.

**Comment by Apacelus** [comment]
Ill go start the build now. @mmccall0813 just update your system in 10mins

**Comment by mmccall0813** [comment]
Works great, thanks!
