### ISSUE TITLE
syntaxerror 

### ISSUE THREAD

**Issue by yirod3721** [eupnea-linux/audio-scripts#54]
**Describe the bug**
File "/home/yazan3721/audio-scripts/./setup-audio", line 153
    match platform:
          ^
SyntaxError: invalid syntax

**Device (please complete the following information):**
 - Distro [e.g. Fedora, Ubuntu]:BerryliumOS
 - DE [e.g. gnome, kde]:Openbox
 - Version [e.g. 22.04]:
 - Device codename [Find it on the developer screen]: REEF
 - Running EupneaOS/Depthboot [yes/no]:no

**Comment by Apacelus** [comment]
You need >=python3.10 to run this script

**Comment by yirod3721** [comment]
i have python3.10

**Comment by Apacelus** [comment]
What is the output of `python3 --version`

**Comment by Apacelus** [comment]
Also, what is BerriliumOS? Does it have a website or something?
