### ISSUE TITLE
Support for taniks (Alder Lake CPU)?

### ISSUE THREAD

**Issue by wtongze** [eupnea-linux/audio-scripts#55]
Hi there,
I have recently bought a chromebook with code name "taniks" (Lenovo IdeaPad Gaming 16"). It uses an Alder Lake CPU. The audio is currently listed as Unsupported. I wondering is there any plan to support this device in the future?

Thanks

**Comment by WeirdTreeThing** [comment]
Wait a few hours and I can add support for your device.

**Comment by WeirdTreeThing** [comment]
I have just added support for your board, but you will need to wait for the packages to rebuild.
