### ISSUE TITLE
Chromebook Flip C434 (Shyvana) - Audio & Bluetooth  Issues

### ISSUE THREAD

**Issue by Zendeuo** [eupnea-linux/audio-scripts#59]
**Describe the bug**

**Device: Chromebook Flip C434**
 - Distro: Ubuntu
 - DE: GNOME
 - Version: 23.04
 - Device codename: Shyvana 
 - Running EupneaOS/Depthboot: Yes

**logs**

[2023-05-13_18h-17m-eupnea-logs.tar.gz](https://github.com/eupnea-linux/audio-scripts/files/11470240/2023-05-13_18h-17m-eupnea-logs.tar.gz)

**Additional context**
The audio works on everything but the internal speakers within the ASUS device, I'm hoping you can work on this and possibly fix it as well as Bluetooth since it can sometimes find devices but it doesn't pair them :(

**Comment by WeirdTreeThing** [comment]
You need ChromeOS kernel for speakers to work, the script says this. To get the ChromeOS kernel install `eupnea-chromeos-kernel` with your package manager.

**Comment by Zendeuo** [comment]
OMG tysm I didn't even know, I hope it'll be more documented, or maybe I might have skipped over it so I apologise but it works and it's fully functional now tysmmm :3
